### ISSUE TITLE
Missing imports in CleverPushCapacitorPlugin.java

### ISSUE THREAD

**Issue by DavRet** [cleverpush/cleverpush-capacitor-sdk#21]
Hello,

it seems that **CleverPushCapacitorPlugin.java** is missing imports for **"PluginHandle"** and **"Bridge"** after commit https://github.com/cleverpush/cleverpush-capacitor-sdk/commit/e608a80586a85e31f795a331fc58a8f52b88e7ca.

When compiling on the Android platform, we're getting the following errors:

- cannot find symbol class Bridge
- cannot find symbol class PluginHandle

After importing it manually it works fine:

`import com.getcapacitor.PluginHandle;`
`import com.getcapacitor.Bridge;`

Best regards
David

**Comment by unnaticleverpush** [comment]
Thanks for reporting! Fixed with https://github.com/cleverpush/cleverpush-capacitor-sdk/pull/23 and released with version 1.3.17

**Comment by unnaticleverpush** [comment]
Thanks for reporting! Fixed with https://github.com/cleverpush/cleverpush-capacitor-sdk/pull/23 and released with version 1.3.17

**Comment by DavRet** [comment]
Any plans when the new version will be released?

**Comment by gbhrdt** [comment]
@DavRet  we will release the new version tomorrow and update you, thanks for your patience!

**Comment by unnaticleverpush** [comment]
@DavRet It's released with version 1.3.17
