### ISSUE TITLE
ExceptionCode "UNIMPLEMENTED" on iOS Capacitor 6 build

### ISSUE THREAD

**Issue by DavRet** [cleverpush/cleverpush-capacitor-sdk#22]
Hello,

Since updating Capacitor from v4 to v6, the CleverPush plugin isn't working on iOS, though it works fine on Android, except for https://github.com/cleverpush/cleverpush-capacitor-sdk/issues/21.

We're using:

@capacitor/ios v6.1.1
cleverpush-capacitor-sdk 1.3.16

Attempting to subscribe with:

`CleverPush.subscribe()
  .then(result => {
    console.log("Subscription ID:", result.subscriptionId);
  })
  .catch(error => {
    console.error("Subscription failed:", error);
  });`

results in:
  
  `[error] - Subscription failed: {"code":"UNIMPLEMENTED"}
`

The error occurs for all methods.

We've re-applied setup instructions from the CleverPush setup guide without success.
Are we missing something here?

Any help is much appreciated!

Best regards
David

**Comment by unnaticleverpush** [comment]
Thanks for reporting! Fixed with https://github.com/cleverpush/cleverpush-capacitor-sdk/pull/24 and released with version 1.3.17
